package grade.optimizer;

public class ClassPanel extends javax.swing.JPanel {

    final String title;
    final float points;
    /**
     * Creates new form ClassPanel
     */
    public ClassPanel(String title, float points, int grade) {
        this.title = title;
        this.points = points;
        initComponents();
        if(grade >= 0)
            gradeJTF.setText(Integer.toString(grade));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLBL = new javax.swing.JLabel();
        maxPointsLBL = new javax.swing.JLabel();
        gradeJTF = new javax.swing.JTextField();
        givenPointsLBL = new javax.swing.JLabel();

        nameLBL.setText(title);

        maxPointsLBL.setText(Float.toString(points)
        );

        gradeJTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                gradeJTFFocusLost(evt);
            }
        });

        givenPointsLBL.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nameLBL, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(maxPointsLBL)
                .addGap(18, 18, 18)
                .addComponent(gradeJTF, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(givenPointsLBL)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameLBL)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(maxPointsLBL)
                        .addComponent(gradeJTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(givenPointsLBL)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void gradeJTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_gradeJTFFocusLost
        // Send the trigger that the grades have changed
        if(updateScore()){
            MainGUI.instance.updateGrades();
        }
    }//GEN-LAST:event_gradeJTFFocusLost

    public int getGrade(){
        if(gradeJTF.getText().replaceAll("[^0-9]", "").equals(gradeJTF.getText()) && !gradeJTF.getText().equals(""))
            return Integer.parseInt(gradeJTF.getText());
        return -1;
    }
    
    public boolean updateScore(){
        if(gradeJTF.getText().replaceAll("[^0-9]", "").equals(gradeJTF.getText()) && !gradeJTF.getText().equals("")){
            givenPointsLBL.setText(Float.toString(points*(Float.parseFloat(gradeJTF.getText())/100)));
            return true;
        }
        return false;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel givenPointsLBL;
    private javax.swing.JTextField gradeJTF;
    private javax.swing.JLabel maxPointsLBL;
    private javax.swing.JLabel nameLBL;
    // End of variables declaration//GEN-END:variables
}
